"use strict";
// automatically generated by the FlatBuffers compiler, do not modify
Object.defineProperty(exports, "__esModule", { value: true });
exports.FrameType = void 0;
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
var FrameType;
(function (FrameType) {
    FrameType[FrameType["Full"] = 0] = "Full";
    FrameType[FrameType["Delta"] = 1] = "Delta";
})(FrameType || (exports.FrameType = FrameType = {}));
