// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FRAME_FUTABA_H_
#define FLATBUFFERS_GENERATED_FRAME_FUTABA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Futaba {

struct Frame;
struct FrameBuilder;

enum FrameType : int8_t {
  FrameType_Full = 0,
  FrameType_Delta = 1,
  FrameType_MIN = FrameType_Full,
  FrameType_MAX = FrameType_Delta
};

inline const FrameType (&EnumValuesFrameType())[2] {
  static const FrameType values[] = {
    FrameType_Full,
    FrameType_Delta
  };
  return values;
}

inline const char * const *EnumNamesFrameType() {
  static const char * const names[3] = {
    "Full",
    "Delta",
    nullptr
  };
  return names;
}

inline const char *EnumNameFrameType(FrameType e) {
  if (::flatbuffers::IsOutRange(e, FrameType_Full, FrameType_Delta)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesFrameType()[index];
}

struct Frame FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FrameBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_DATA = 6,
    VT_CRC32 = 8
  };
  Futaba::FrameType type() const {
    return static_cast<Futaba::FrameType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  uint32_t crc32() const {
    return GetField<uint32_t>(VT_CRC32, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           VerifyField<uint32_t>(verifier, VT_CRC32, 4) &&
           verifier.EndTable();
  }
};

struct FrameBuilder {
  typedef Frame Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(Futaba::FrameType type) {
    fbb_.AddElement<int8_t>(Frame::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(Frame::VT_DATA, data);
  }
  void add_crc32(uint32_t crc32) {
    fbb_.AddElement<uint32_t>(Frame::VT_CRC32, crc32, 0);
  }
  explicit FrameBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Frame> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Frame>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Frame> CreateFrame(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Futaba::FrameType type = Futaba::FrameType_Full,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0,
    uint32_t crc32 = 0) {
  FrameBuilder builder_(_fbb);
  builder_.add_crc32(crc32);
  builder_.add_data(data);
  builder_.add_type(type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Frame> CreateFrameDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    Futaba::FrameType type = Futaba::FrameType_Full,
    const std::vector<uint8_t> *data = nullptr,
    uint32_t crc32 = 0) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return Futaba::CreateFrame(
      _fbb,
      type,
      data__,
      crc32);
}

inline const Futaba::Frame *GetFrame(const void *buf) {
  return ::flatbuffers::GetRoot<Futaba::Frame>(buf);
}

inline const Futaba::Frame *GetSizePrefixedFrame(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Futaba::Frame>(buf);
}

inline bool VerifyFrameBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Futaba::Frame>(nullptr);
}

inline bool VerifySizePrefixedFrameBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Futaba::Frame>(nullptr);
}

inline void FinishFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Futaba::Frame> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedFrameBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Futaba::Frame> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Futaba

#endif  // FLATBUFFERS_GENERATED_FRAME_FUTABA_H_
